# Generated by Django 4.0.3 on 2022-03-15 23:09

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='resumo',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='texto',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
